name: Run tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v3.3.0
      with:
        distribution: 'zulu'
        java-version: '8'

    - uses: DeLaGuardo/setup-clojure@5.1
      with:
        tools-deps: latest

    - uses: actions/checkout@v3.0.2

    - name: Cache clojure dependencies
      uses: actions/cache@v3.0.4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
        key: clojure-${{ hashFiles('**/deps.edn') }}
        restore-keys: "clojure-"

    - name: Run tests
      run: |
        clojure -X:test
